#!/usr/bin/env python3
"""
Yoga Poses Wiki Wiki Auto-Generator
Generated by create_niche_wiki.py
"""
import os, json, time, datetime, urllib.request, urllib.error, re

SITE_URL   = "https://t307239.github.io/yoga-wiki"
AMAZON_TAG = "bjj06-22"
GA4_ID     = "G-7LM8L3TRZM"
ADSENSE    = "ca-pub-5529701443220352"

TECHNIQUES = [
    "Downward Dog",
    "Warrior I",
    "Warrior II",
    "Tree Pose",
    "Cobra Pose",
    "Mountain Pose",
    "Bridge Pose",
    "Chair Pose",
    "Pigeon Pose",
    "Camel Pose",
    "Fish Pose",
    "Headstand",
    "Crow Pose",
    "Eagle Pose",
    "Warrior III",
    "Side Plank",
    "Boat Pose",
    "Bow Pose",
    "Wheel Pose",
    "Lizard Pose",
    "Low Lunge",
    "Garland Pose",
    "Firefly Pose",
    "Shoulder Stand",
    "Sun Salutation",
    "Cat Cow",
    "Locust Pose",
    "Happy Baby",
    "Seated Forward Bend"
]

GEMINI_MODELS = ["gemini-2.0-flash","gemini-1.5-flash","gemini-2.5-flash-preview-04-17"]

def slugify(name):
    return re.sub(r"[^a-z0-9]+","-",name.lower()).strip("-")

def gemini_generate(prompt, api_key):
    for model in GEMINI_MODELS:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
        data = json.dumps({"contents":[{"parts":[{"text":prompt}]}]}).encode()
        req = urllib.request.Request(url, data=data,
            headers={"Content-Type":"application/json"}, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                res = json.loads(r.read())
            text = res["candidates"][0]["content"]["parts"][0]["text"]
            m = re.search(r"\{.*\}", text, re.DOTALL)
            if m:
                return json.loads(m.group(0))
        except Exception as e:
            print(f"  {model} failed: {e}")
            continue
    return None

def build_article(tech_name, lang, api_key):
    slug = slugify(tech_name)
    prompt = f"""Write a comprehensive Yoga Pose guide for "{tech_name}" in {lang}.
Return JSON:
{{
  "title": "SEO optimized page title",
  "meta_description": "155 char description",
  "intro": "2-3 sentence introduction",
  "steps": ["step 1", "step 2", "step 3", "step 4", "step 5"],
  "tips": "2-3 pro tips",
  "variations": ["variation 1", "variation 2"],
  "faq_q": "Common question",
  "faq_a": "Answer to the question"
}}"""
    return gemini_generate(prompt, api_key)

def build_html(tech_name, article, lang, slug):
    title   = article.get("title", tech_name)
    desc    = article.get("meta_description","")
    intro   = article.get("intro","")
    steps   = article.get("steps",[])
    tips    = article.get("tips","")
    faqs    = article.get("faq_q",""), article.get("faq_a","")
    
    now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S+09:00")
    
    steps_html = "\n".join(
        f'<div class="step"><div class="step-num">{i+1}</div><div>{s}</div></div>'
        for i,s in enumerate(steps)
    )
    
    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta property="og:title" content="{title}">
<meta property="og:image" content="{SITE_URL}/og-image.svg">
<link rel="canonical" href="{SITE_URL}/{lang}/{slug}.html">
<link rel="alternate" hreflang="x-default" href="{SITE_URL}/en/{slug}.html">
<link rel="alternate" hreflang="en" href="{SITE_URL}/en/{slug}.html">
<link rel="alternate" hreflang="ja" href="{SITE_URL}/ja/{slug}.html">
<link rel="alternate" hreflang="pt" href="{SITE_URL}/pt/{slug}.html">
<script async src="https://www.googletagmanager.com/gtag/js?id={GA4_ID}"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{GA4_ID}');</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client={ADSENSE}" crossorigin="anonymous"></script>
<script type="application/ld+json">
{{
  "@context":"https://schema.org","@type":"Article",
  "headline":"{title}","description":"{desc}",
  "datePublished":"2026-03-13T00:00:00+09:00",
  "dateModified":"{now}",
  "url":"{SITE_URL}/{lang}/{slug}.html",
  "publisher":{{"@type":"Organization","name":"Yoga Poses Wiki Wiki","url":"{SITE_URL}/"}}
}}
</script>
<style>
:root{{--bg:#080b12;--card:#141926;--border:#1f2840;--text:#e8eaf6;--muted:#6b7699;--accent:#7c6af7;--accent2:#a78bfa}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:var(--bg);color:var(--text);font-family:-apple-system,sans-serif;line-height:1.75;padding:0 16px}}
.container{{max-width:860px;margin:0 auto;padding-bottom:80px}}
h1{{font-size:2rem;font-weight:800;margin:12px 0 16px}}
h2{{font-size:0.9rem;font-weight:700;color:var(--accent2);text-transform:uppercase;letter-spacing:.08em;margin:32px 0 12px}}
.card{{background:var(--card);border:1px solid var(--border);border-radius:12px;padding:20px;margin-bottom:16px}}
.step{{display:flex;gap:14px;padding:8px 0}}
.step-num{{min-width:28px;height:28px;border-radius:50%;background:var(--accent);color:#fff;display:flex;align-items:center;justify-content:center;font-size:0.8rem;font-weight:700}}
footer{{margin-top:48px;padding-top:24px;border-top:1px solid var(--border);text-align:center;color:var(--muted);font-size:0.85rem}}
</style>
</head>
<body>
<div class="container">
<header style="padding:20px 0;border-bottom:1px solid var(--border);margin-bottom:32px">
  <a href="../index.html" style="font-size:1.3rem;font-weight:800;color:var(--text);text-decoration:none">
    Yoga Poses Wiki<span style="color:var(--accent)">Wiki</span>
  </a>
</header>
<h1>{title}</h1>
<p style="color:#b0b8d4;font-size:1.05rem;margin-bottom:32px">{intro}</p>
<h2>Step-by-Step Guide</h2>
<div class="card">{steps_html}</div>
<h2>Pro Tips</h2>
<div class="card"><p>{tips}</p></div>
<div style="background:linear-gradient(135deg,#0f1a0f,#0a1a0a);border:1px solid #2d5a2d;border-radius:12px;padding:20px;margin:24px 0;text-align:center">
  <a href="https://www.amazon.com/s?k={{tech_name.replace(' ','+')}}&tag={AMAZON_TAG}" target="_blank" rel="noopener noreferrer nofollow"
     style="display:inline-block;background:#ff9900;color:#111;padding:10px 24px;border-radius:8px;font-weight:700">
    🛒 Shop {tech_name} on Amazon
  </a>
</div>
<div class="card">
  <p><strong>Q: {faqs[0]}</strong></p>
  <p style="margin-top:8px">{faqs[1]}</p>
</div>
<footer><p>Yoga Poses Wiki Wiki — Free multilingual encyclopedia</p></footer>
</div>
</body>
</html>"""

def main():
    api_key = os.environ.get("GEMINI_API_KEY","")
    if not api_key:
        try:
            with open(os.path.expanduser("~/.secrets")) as f:
                for line in f:
                    if line.startswith("GEMINI_API_KEY="):
                        api_key = line.split("=",1)[1].strip()
        except: pass
    
    if not api_key:
        print("❌ GEMINI_API_KEY required")
        return
    
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--limit", type=int, default=5)
    args = parser.parse_args()
    
    base = os.path.dirname(__file__).replace("/scripts","")
    
    generated = json.load(open(base+"/generated.json")) if os.path.exists(base+"/generated.json") else {}
    
    todo = [t for t in TECHNIQUES if slugify(t) not in generated][:args.limit]
    print(f"Generating {len(todo)} articles...")
    
    for tech in todo:
        slug = slugify(tech)
        for lang in ["en","ja","pt"]:
            out_dir = os.path.join(base, lang)
            os.makedirs(out_dir, exist_ok=True)
            out_path = os.path.join(out_dir, slug+".html")
            if os.path.exists(out_path):
                continue
            print(f"  {lang}/{slug}")
            article = build_article(tech, lang, api_key)
            if article:
                html = build_html(tech, article, lang, slug)
                with open(out_path,"w") as f:
                    f.write(html)
            time.sleep(1)
        generated[slug] = True
    
    with open(base+"/generated.json","w") as f:
        json.dump(generated, f)
    print("Done")

if __name__ == "__main__":
    main()
